version: "3"

services:
    mydb:
      image: 'mongo'
      ports:
        - "27017:27017"
    bookstore:
      build: 
        context: .
        dockerfile: 'Conference.Web/Dockerfile'
      environment:
         - "MongoConnection__ConnectionString=mongodb://localhost:27017"
         - "MongoConnection__DatabaseName=Conference"
      ports:
      - "5000:5000"
      - "5001:5001"
